### ISSUE TITLE
Are colors supported in Linux containers logs?

### ISSUE THREAD

**Issue by VeselovAndrey** [spectreconsole/spectre.console#1322]
**Information**
 - OS: .NET 7 in Linux container (mcr.microsoft.com/dotnet/aspnet:7.0, under Docker Desktop for Windows, web project with Minimal API)
 - Terminal: Built-in

**Describe the bug**
According to AnsiConsole.Profile.Capabilities ColorSystem.EightBit supported.
But I see no colors in output.

BTW at same time Docker supports colors as I saw colored logs output for some containers.

**To Reproduce**
Run something like
AnsiConsole.Write(new Rule("[yellow bold underline]8-bit Colors[/]").RuleStyle("grey").LeftJustified());
in container app

**Expected behavior**
Colored output.
If containers are not supported it will be nice to clearly mentioned it in docs.

**Comment by nils-a** [comment]
I guess you are not running windows containers. (Simply because I never met anyone who does.)

The ability to render different colors is dependent on the terminal, not on the OS or any particular container. 
On Linux-based systems, we rely on known terminals to detect the ability to process ANSI codes.
Running a container in docker does not set the `TERM` environment variable. (At least not for me, running docker on WSL)

So, if you are on a Linux OS (or running cygwin on Windows, or a real XTerm on WSL, or Alacritty, or in short, have a terminal where the `TERM` environment variable is correctly set), you can most probably simply append `-e TERM` to your docker commandline, and you will get ANSI escape codes enabled according to the terminal you are running, and thus you will most likely see some colors.

If you are running docker on Windows in a Windows terminal, you can try to append `-e TERM:xterm` to give spectre.console in the container a hint of your capabilities. However, make sure you are running in a terminal that does support rendering the ANSI codes. If you don't, and still set `TERM` you'll probably see plenty of cryptic codes in the output.

So, to answer the question you raised in the title: Yes-And-No, the attached terminal may or may not have support for colors. The container itself is "color agnostic".

**Comment by VeselovAndrey** [comment]
@nils-a Thank you for detailed response. Maybe it worth to add to docs so more peoples will know that.

**Comment by nils-a** [comment]
Tracking as #1329
