### ISSUE TITLE
Table line separators not showing for the first line when table headers are hidden

### ISSUE THREAD

**Issue by MoaidHathot** [spectreconsole/spectre.console#1391]
**Information**
 - OS: Windows 11 23H2 (OS Build 22631.2506)
 - Version: Spectre.Console 0.48.0
 - Terminal: Windows Terminal 1.19.3172.0

**Describe the bug**
When table headers are hidden, the first row separator is not drawn.

**To Reproduce**
```csharp
var table = new Table();

table.AddColumn("First");
table.AddColumn("Second");

table.AddRow("1", "2");
table.AddRow("3", "4");
table.AddRow("5", "6");

table.ShowRowSeparators = true;
table.HideHeaders();

AnsiConsole.Write(table);
```
**Expected behavior**
The first row separator should be visible even if table headers are hidden

**Screenshots**
![image](https://github.com/spectreconsole/spectre.console/assets/8770486/3f81a05b-4716-4351-92cc-b9735d863ef0)

**Comment by BlazeFace** [comment]
Hello! I'm proposing a fix for this issue, [[Commit c63b842 ](https://github.com/BlazeFace/spectre.console/commit/](https://github.com/BlazeFace/spectre.console/commit/c63b842645f116a26bf6c45a69a94da15c0a866b) . The edge case causing this is that the code assumes that headers are shown and does not render the first separator, the fix is to check if headers are hidden and if so render the separator! Let me know if I need to make any other changes as this is my first contribution @patriksvensson .

**Comment by BlazeFace** [comment]
@FrankRay78 I think I have a pretty complete solution for this, should I go ahead and make a PR?

**Comment by FrankRay78** [comment]
By all means @BlazeFace, please do. I normally maintain the CLI subsystem, but I can review/merge all PR's. I'll use this as an opportunity to upskill myself on the table widget.
