### ISSUE TITLE
Missing examples in documentation for text prompt

### ISSUE THREAD

**Issue by OronDF343** [spectreconsole/spectre.console#1615]
[Link](https://spectreconsole.net/prompts/text)

There are no code examples on this page.

**Comment by FrankRay78** [comment]
@OronDF343 Has the lack of examples stopped you from using the text prompt? If not, how did you figure out the usage? (I'm trying to triage the priority of this issue)

**Comment by Mehybinator** [comment]
@FrankRay78 speaking of my personal experience on the issue, the lack of examples on the main website lead me to the github to try and figure out how to use it, my eyes glanced at the examples folder and so i opend it and saw the prompts example, one thing i figured out was that there are some options, one i can use AnsiConsole.Ask to ask a question in the terminal, but also the same thing could be implemented by just puting a new TextPrompt in a Prompt, which beged the question wether its even needed to use the Ask because you might need to customize the prompt for example to allow empty strings and defaults which are not included in Ask, but also imo there arent a lot of variations of the uses of each class, which is not a problem but i would've loved to see anything but text being used in panels and layouts, another issue i found was that there is no spot on the main website for Altscreen, i found out about it in the examples folder too, so thats my experience. i am a begginer to C# and im trying to implement an application i've made in C# which was originally written in go, and the reason is basically this project, so i would love to send my thanks to the team behind Spectre.Console, stay safe.

**Comment by FrankRay78** [comment]
Thanks @OronDF343, @Mehybinator, that's really helpful. I've long suspected the examples solution would benefit from more prominence. I know it's mentioned on the main GitHub readme, but I think we only directly link to examples from two pages in the main spectre website, and these are DI and the help writer, not any widget pages. I'm going to have a little think how this might be improved for new devs using the library.

**Comment by davide-pi** [comment]
Thanks @FrankRay78, [here](https://github.com/spectreconsole/spectre.console/pull/1636/) you can find the PR.
I've also leaved a comment for you in the example I've mentioned above, about the `Optional` TextPrompt.

**Comment by davide-pi** [comment]
Hi, @FrankRay78 I think this could be closed.
@OronDF343 Please check the doc and let us know if it meets what you requested 🙇

**Comment by patriksvensson** [comment]
Resolved in #1636
