### ISSUE TITLE
Allow default command configuration for a branch

### ISSUE THREAD

**Issue by DarthPedro** [spectreconsole/spectre.console#187]
If I define a branch with multiple commands, I would like to also configure a default to be called when the root of the branch is used. For example, in the following command configuration:
```
                config.AddBranch("student", student =>
                {
                    student.SetDescription("View, list, add or remove students.");

                    student.AddCommand<StudentAddCommand>("new")
                        .WithAlias("add")
                        .WithDescription("Add new student information.")
                        .WithExample(new[] { "student", "new", "1001", "Bill", "Shakespeare", "--enrollment", "5/14/1549" });

                    student.AddCommand<StudentViewCommand>("view")
                        .WithDescription("View student information by id.")
                        .WithExample(new[] { "student", "view", "1001" });

                    student.AddCommand<StudentListCommand>("list")
                        .WithDescription("View list of students.")
                        .WithExample(new[] { "student", "list" });

                    student.AddCommand<StudentDeleteCommand>("delete")
                        .WithAlias("del")
                        .WithDescription("Remove student from list.")
                        .WithExample(new[] { "student", "delete", "1001" });
                });
```
I would like to set a default in the student configurator, like the following:
`                    student.SetDefaultCommand<StudentListCommand>();
`
That way if the user types the command: myapp student; the program would process the StudentListCommand.
Currently without the default, it shows the student help text.

@patriksvensson I would love to start contributing some fixes to this library. If there are easy bugs to fix, like the ones I've posted, that might be a good place to start.

**Comment by MarcoSpoenemann** [comment]
Hey, at first, thank you for your nice work @patriksvensson! 
Any progress with this issue @DarthPedro? Would be nice if this feature is implemented.

**Comment by FrankRay78** [comment]
I'd like to take this one @patriksvensson - please assign it to me.

**Comment by FrankRay78** [comment]
> @DarthPedro Great idea! I see no immediate gotchas with doing this as long the default command belongs to a branch.

AND

> Yes, I'll give this one a shot. Seems like it would fairly straightforward to add. 

Indeed, I thought the same.  Now that I've written much of the supporting code and unit tests for this feature, I have hit the actual challenging part - namely, when parsing the command line arguments, knowing exactly when a branch's default command is required and should be "inserted" into the `CommandModel`

As an example, take the following unit test:

```csharp
        [Fact]
        public void Should_Run_The_Default_Command_On_Branch()
        {
            // Given
            var app = new CommandAppTester();
            app.Configure(config =>
            {
                //config.UseStrictParsing();
                config.PropagateExceptions();
                config.AddBranch<AnimalSettings>("animal", animal =>
                {
                    animal.SetDefaultCommand<HorseCommand>();
                });
            });

            // When
            var result = app.Run(new[]
            {
                "animal", "4", "--name", "Arkle",
            });

            // Then
            result.ExitCode.ShouldBe(0);
            result.Settings.ShouldBeOfType<MammalSettings>().And(horse =>
            {
                horse.Legs.ShouldBe(4);
                horse.Name.ShouldBe("Arkle");
            });
        }
```

When strict parsing is off, `app.Run` completes successfully as `CommandTreeParser.ParseOptionValue(...)` adds `--name Arkle` to the remaining arguments without error, see this line:

```csharp
        else
        {
           context.AddRemainingArgument(token.Value, parseValue ? valueToken.Value : null);
        }
```

I can turn strict parsing on so that an exception is thrown at the first indication of something being wrong/unexpected in the parsing, meaning that `app.Run` in the above test would result in `CommandTreeParser.ParseOptionValue(...)` hitting the following line:

```csharp
        if (context.ParsingMode == ParsingMode.Strict)
        {
            throw CommandParseException.UnknownOption(context.Arguments, token);
        }
```

One solution could be to wrap the `CommandTreeParser` calls in `CommandExecutor` in try catches, catching parsing exceptions and determining when to instead try inserting the default commmand name into the argument collection in the appropriate position, before calling the `CommandTreeParser` again to see if that parses correctly. Aside from not seeming to be a great implementation, this solution would require StrictParsing to be turned on once a default command has been specified for a branch, which may not be satisfactory behaviour. Additionally, I suspect that allowing default commands at branches many levels deep may add a level of complexity.

I've been scratching my head as to alternatives, but the complexity faced here fundamentally lies in having command line arguments, passed in by the user, with branches at potentially many levels, and with strict parsing turned off, the default behaviour being to add anything that doesn't fit the parsing model, to the remaining arguments, and hiding the fact that a default command should be deferred to.

**Comment by FrankRay78** [comment]
I have now implemented the changes required for this issue, currently located on the following branch: https://github.com/FrankRay78/spectre.console/tree/187-Allow-default-command-configuration-for-a-branch-WIP

I just need to do a quick review of whether the branch command help text ie. `HelpWriter.WriteCommand(...)` needs to be updated to include a description of the default command (when one is present), before opening a PR.

**Comment by FrankRay78** [comment]
FYI. I've raised https://github.com/spectreconsole/spectre.console/pull/1101 which fixes this issue.
