### ISSUE TITLE
Support options before arguments

### ISSUE THREAD

**Issue by agc93** [spectreconsole/spectre.console#193]
Especially for Unix/Linux platforms, the convention is usually to provide options before arguments:

```bash
Usage: grep [OPTION]... PATTERN [FILE]...
Usage: tar [OPTION...] [FILE]...
systemctl [OPTIONS...] {COMMAND} ...
```

Using boolean options before arguments currently gets incorrectly interpreted as assigning a value to the option flag. Would be good to support this ordering (preferably alongside existing behaviour).

**Comment by woutervanranst** [comment]
FYI I came here after looking through all issues. I believe the related error message is 
```
       restore --keep-pointers c:\Users\Wouter\Documents\Test
               ^^^^^^^^^^^^^^^ Can't assign value

CommandParseException: Flags cannot be assigned a value.
```

+1 on supporting the Linux/CLI convention

**Comment by dswisher** [comment]
Even as a developer, I was quite confused by the "Can't assign value" error message. Ideally, options would be allowed before arguments, but at the very least, could the error message be improved?

**Comment by NJ-Brad** [comment]
I found this to be an issue with users learning the system.  The help option is frequently used by people learning a system 
`Myapp --help somecommand` triggers the main help IE
`Myap --help`

This is especially an issue since the help that is displayed, shows the usage as
`Myapp [OPTIONS] <COMMAND>`

**Comment by FrankRay78** [comment]
Cake has an open issue for this, https://github.com/cake-build/cake/issues/3280, basically looking to move all the cake command options before the build script argument, allowing any options following the command argument to automatically become remaining arguments.

**Comment by FrankRay78** [comment]
This issue is occuring due to the way that CommandTreeParser is handling Options, namely peeking ahead to the next argument to determine what to do.

The following image is when I've specified the following on the command line `--version --somethingelse` and it's currently parsing the --version Option.  you can see that it's peeked ahead and discovered another Option:

![image](https://user-images.githubusercontent.com/52075808/196495537-cd3e256d-ee65-42d7-887e-2d41b7e01c4e.png)

It knows to correctly ignore the following `somethingelse` Option and just proceed with the 'No value?' code further on.

When I specify the following on the command line `--version somethingelse`, then when it is parsing the --version Option, it peeks ahead and discovers something following it of TokenKind String:

![image](https://user-images.githubusercontent.com/52075808/196496744-fc850a1b-6a7c-4e36-a703-cc12c6963b34.png)

CommandTreeParser.ParseOptionValue proceeds to attempt to set the --version Option to this value, unsuccessfully:

![image](https://user-images.githubusercontent.com/52075808/196497071-8b318b42-69cd-474d-8137-943ab6c35bd0.png)

---

For @woutervanranst 's example above to work correctly,

```restore --keep-pointers c:\Users\Wouter\Documents\Test```

I guess the CommandTreeParser needs to 

1. check if `--keep-pointers` is a flag (ie. boolean value specified on the command settings class)
2. if yes, then ignore the peek, proceed with the 'No value?' code further on, and parse `c:\Users\Wouter\Documents\Test` on the next pass (which should be handled here I suspect:) 
![image](https://user-images.githubusercontent.com/52075808/196499292-0bee3223-155e-492b-bc60-078a500f8f63.png)
3. if no, then attempt to set the `--keep-pointers` option value to `c:\Users\Wouter\Documents\Test`

**Comment by woutervanranst** [comment]
I m assuming we don t need to reinvent the wheel here, I expect there are nasty edge cases we re missing - linux CLI parsers would have solved this already

**Comment by patriksvensson** [comment]
@FrankRay78 Done!

**Comment by FrankRay78** [comment]
This issue can be closed/marked as complete @patriksvensson, now that PR https://github.com/spectreconsole/spectre.console/pull/1048 has been successfully merged.
