### ISSUE TITLE
[CLI] Argument array overridden with `null` if no arguments provided

### ISSUE THREAD

**Issue by MiloszKrajewski** [spectreconsole/spectre.console#422]
**Information**
 - OS: Win 10
 - Versions: 
   - 0.37.1-preview.0.39, 
   - 0.39.0, 
   - 0.39.1-preview.0.21
 - Terminal: Windows Terminal

**Describe the bug**
When I use argument array I initialize it with `Array.Empty<T>` so I don't have to handle nulls in logic.

```c#
public class Settings: CommandSettings
{
	[CommandArgument(0, "[NAME...]")]
	public string[] Names { get; set; } = Array.Empty<string>(); // I'm initializing it with empty array...
}
```

**To Reproduce**

```c#
public class MyCommand: Command<MyCommand.Settings>
{
	public class Settings: CommandSettings
	{
		[CommandArgument(0, "[NAME...]")]
		public string[] Names { get; set; } =
			Array.Empty<string>(); // I'm initializing it with empty array...
	}

	public override int Execute(CommandContext context, Settings settings) =>
		settings.Names is null 
			? -1 // ...but it gets overriden with null 
			: settings.Names.Length;
}

static class Program
{
	static void Main(string[] args)
	{
		var app = new CommandApp();
		app.Configure(c => c.AddCommand<MyCommand>("do"));
		
		var result3 = app.Run(new[] { "do", "a", "b", "c" });
		Debug.Assert(result3 == 3);
		
		var result0 = app.Run(new[] { "do" });
		Debug.Assert(result0 == 0); // -1 vs 0
	}
}
```

**Expected behavior**
If not arguments are given (`app.Run(new[] { "do" });`) I expect `settings.Names` to be `Array.Empty<string>` not `null`. 

**Actual behavior**
When I give 3 arguments (`app.Run(new[] { "do", "a", "b", "c" });`) I see `3` returned as result. Good. 
When no arguments are given `settings.Names` is overriden with `null`.
It is a regression as it was working as expected in `0.37.1-preview.0.39` but not anymore in `0.39.0` nor `0.39.1-preview.0.21`.

**Screenshots**
N/A

**Additional context**
[spectre-null-fields.zip](https://github.com/spectreconsole/spectre.console/files/6514766/spectre-null-fields.zip)

**Comment by phil-scott-78** [comment]
Due to how Spectre instantiates the settings we are ignoring property initializers. Right now, your best is going to be using a constructor and a null check there. 

```csharp
public sealed class Settings : CommandSettings
{
    public Settings(string[] values)
    {
        Values = values ?? Array.Empty<string>();
    }

    public string[] Values {get;}
}
```

I'll make a note and add a warning about property initialization in the docs though. We need to be clearer about that not working currently.

**Comment by MiloszKrajewski** [comment]
I went for backing field and explicit property getter/setter:

```
private string[] _names;

[CommandArgument(0, "[NAME...]")]
public string[] Names
{
	get => _names ?? Array.Empty<string>();
	set => _names = value;
}
```

so I'm I can live with that.

My question is though, is it design choice and it will stay like this, or it is a regression and will be fixed?

**Comment by phil-scott-78** [comment]
Well, I'm not sure I'd call it a design choice and definitely not a regression. Just a case Patrik or I don't use ourselves so it probably just got missed. 

It seems valid and a doable fix though. I suspect we are overwriting the value in the [CommandPropertyBinder.cs](https://github.com/spectreconsole/spectre.console/blob/main/src/Spectre.Console/Cli/Internal/Binding/CommandPropertyBinder.cs). It might be as simple as skipping the assign if the value is null. 

Testing around this code is pretty solid if you want to try and get a PR with this improvement and appropriate unit tests. Otherwise I might give it a try later next week when I should have some free time to dig in.
