### ISSUE TITLE
Option to remove rows or columns from a table

### ISSUE THREAD

**Issue by danielmayost** [spectreconsole/spectre.console#500]
**Is your feature request related to a problem? Please describe.**
'm always frustrated when I want to remove and update field content or remove rows from a table, to use "Live". 

**Describe the solution you'd like**
Remove rows or columns, and update content in a specific field in the table. 

**Describe alternatives you've considered**
Right now, every time you need to create a new table, and recast the desired content out of it. I have no other alternative.

**Comment by danielmayost** [comment]
I use the code I added to myself, why did you not include it in the first place?

Code: https://github.com/danielmayost/spectre.console/blob/main/src/Spectre.Console/Widgets/Table/Table.cs

**Comment by phil-scott-78** [comment]
> I use the code I added to myself, why did you not include it in the first place?
> 

The code was not included because it was not yet written. 

With the live functionality in place I think it's a good feature to add. I'll take a look at what you have later tonight after my kid goes to sleep. If things look good I think a pull request and review would be in order and we can add it to the next release?

**Comment by danielmayost** [comment]
I meant why they did not allow it before.

This is a code I wrote for myself, I do not know if it is good enough for Pull's request.
