### ISSUE TITLE
Customise text prompt for secrets

### ISSUE THREAD

**Issue by lonix1** [spectreconsole/spectre.console#943]
**Is your feature request related to a problem? Please describe.**
The [text prompt](https://spectreconsole.net/prompts/text#secrets) for secrets echoes asterisks (***) to the console.

This is acceptable. But it feels weird on unixy systems, where the traditional secret prompt (`sudo`) echoes nothing.

**Describe the solution you'd like**
It would be nice to be able to customise the masking character. I would set it to `null`, so nothing is echoed to the console.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by GaryMcD** [comment]
I would like to take a stab at this one if possible.

I am thinking....

I would add a `char` to `TextPrompt` that defaults to an asterisk. Maybe named `MaskingCharacter`. And then whenever we are checking if secret is set instead of using the hardcoded asterisk currently in place, we use the masking character.

Looks like I would need to touch these locations in code.

![image](https://user-images.githubusercontent.com/16275325/189512651-ac14c89a-1d9f-4188-b8f5-e82da0758f63.png)

**Comment by patriksvensson** [comment]
I would say `public char? Mask { get; set; } = '*'`

**Comment by GaryMcD** [comment]
Began working on this.

Question.

The following occurs on line 129 and 210 of TextPrompt.cs
`IsSecret ? "******" : converter(DefaultValue.Value)`

I was considering creating a private string with just a get that will create a six character string of whatever the Mask char is, and call that in these two spots instead of the hard coded six asterisk.

Not sure if that's the proper way to resolve?

Then I came to wonder if the string should actually be as long as the default value. So if default value is 5 characters, then the mask of the default value should be 5 characters.

Let me know your thoughts!

**Comment by GaryMcD** [comment]
You can start reviewing what I put together if you like.

https://github.com/spectreconsole/spectre.console/pull/970

**Comment by GaryMcD** [comment]
This has been merged in :) @patriksvensson do we close this?

**Comment by patriksvensson** [comment]
Yes, we should 😁

**Comment by patriksvensson** [comment]
Closed via #970
